function interface(A1,VAl1,beta1,Rc1,Re1,Rb11,Rb21,Rl1,f1,Ie1,val1)

Fig=figure('Name','Tranzistor Bipolar - Conexiunea Emitor-Comun',...
    'Units','normalized',...
    'Position',[0.1 0.1 0.8 0.8],...
    'NumberTitle','off',...
    'Color',[0.2 0.4 0.9]);



VAl=VAl1;               %-----------tensiunea continua de intrare----------
beta=beta1;             %-----------factorul de amplificare in curent------
Rc=Rc1;                 %-----------rezitenta din colector a TB------------
Re=Re1;                 %-----------rezistena din emitor a TB--------------
Rb1=Rb11;               %-----------rezistena 1 din baza a TB--------------
Rb2=Rb21;               %-----------rezistena 2 din baza a TB--------------
Rl=Rl1;                 %-----------rezistena load a TB--------------------
f=f1;                   %-----------frecventa------------------------------
A=A1;                   %-----------amplitudinea semnalului de intrare-----
Ie=Ie1;                 %-----------curentul din emitor--------------------
T=1/f;
t=0:T/100:10*T;
valoare=val1;           %-----------prestabilire a semnalului sinusoidal---
Ic=Ie1;                 %-----------Ie = Ic+Ib = beta*Ib+Ib = Ib*(beta+1) ≈ Ib*beta = Ic



%-----------parametrii de semnal mic 
gm=40.*Ic;                  %-----------------transconductanta diferentiala
rbe=beta./gm;               %rezistenta interna de pe conexiunea Baza-Emitor



%-----------parametrii EC
Av=-gm.*(Rc1.*Rl)./(Rc1+Rl);                      %------amplificarea in tensiune
Ri=(Rb1.*Rb2.*rbe)/(Rb2.*rbe+Rb1.*rbe+Rb1.*Rb2);     %---------rezistenta de intrare
Ro=Rc1;                                           %----------rezistenta de iesire
VO= VAl1-(Ic.*Rc1);



%-----------buton pentru tipuri semnale
Tip_Semnal=uibuttongroup('Visible','on',...
'BackgroundColor','white',...
'ForegroundColor','black',...
'Title','Tipul de semnal',...
'FontSize',12,...
'TitlePosition','centertop',...
'Tag','radiobutton',...
'Position',[0.01 0.8 0.25 0.15]);

uicontrol('Style','radiobutton',...
'Units','normalized',...
'Position',[0 0.5 1 0.5],...
'String','Sinusoidal',...
'Callback','valoare=1,close;interface(A,VAl,beta,Rc,Re,Rb1,Rb2,Rl,f,Ie,valoare);',...
'Parent',Tip_Semnal);

uicontrol('Style','radiobutton',...
'Units','normalized',...
'Position',[0 0 1 0.5],...
'String','Triunghiular',...
'Callback','valoare=2,close;interface(A,VAl,beta,Rc,Re,Rb1,Rb2,Rl,f,Ie,valoare);',...
'Parent',Tip_Semnal);



%-----------butoanele pentru parametrii

Butoane_parametrii=uibuttongroup('Visible','on',...
'BackgroundColor','white',...
'ForegroundColor','black',...
'Title','Parametrii de intrare',...
'FontSize',12,...
'TitlePosition','centertop',...
'Tag','radiobutton',...
'Position',[0.27 0.45 0.25 0.5]);

%-----------buton pentru tensiunea continua a circuitului
uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor','white',...
'ForegroundColor','black',...
'HorizontalAlignment','center',...
'Position',[0.1 0.9 0.2 0.1],...
'String','VAl [V]',...
'Parent',Butoane_parametrii);
uicontrol('Style','edit',...
'Units','normalized',...
'Position',[0.5 0.9 0.3 0.1],...
'String',VAl,...
'Parent',Butoane_parametrii,...
'Callback','VAl=str2num(get(gco,''string'')),close;interface(A,VAl,beta,Rc,Re,Rb1,Rb2,Rl,f,Ie,valoare);');

%-----------buton pentru amplitudinea semnalului de intrare
uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor','white',...
'ForegroundColor','black',...
'HorizontalAlignment','center',...
'Position',[0.1 0.8 0.2 0.1],...
'String','A [V]',...
'Parent',Butoane_parametrii);
uicontrol('Style','edit',...
'Units','normalized',...
'Position',[0.5 0.8 0.3 0.1],...
'String',A,...
'Parent',Butoane_parametrii,...
'Callback','A=str2num(get(gco,''string'')),close;interface(A,VAl,beta,Rc,Re,Rb1,Rb2,Rl,f,Ie,valoare);');

%-----------buton pentru beta
uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor','white',...
'ForegroundColor','black',...
'HorizontalAlignment','center',...
'Position',[0.1 0.7 0.2 0.1],...
'String','Beta',...
'Parent',Butoane_parametrii);
uicontrol('Style','edit',...
'Units','normalized',...
'Position',[0.5 0.7 0.3 0.1],...
'String',beta,...
'Callback','beta=str2num(get(gco,''string'')),close;interface(A,VAl,beta,Rc,Re,Rb1,Rb2,Rl,f,Ie,valoare);',...
'Parent',Butoane_parametrii);

%-----------buton pentru rezistenta din colector
uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor','white',...
'ForegroundColor','black',...
'HorizontalAlignment','center',...
'Position',[0.1 0.6 0.2 0.1],...
'String','Rc [kOhm]',...
'Parent',Butoane_parametrii);
uicontrol('Style','edit',...
'Units','normalized',...
'String',Rc,...
'Position',[0.5 0.6 0.3 0.1],...
'Callback','Rc=str2num(get(gco,''string'')),close;interface(A,VAl,beta,Rc,Re,Rb1,Rb2,Rl,f,Ie,valoare);',...
'Parent',Butoane_parametrii);

%-----------buton pentru rezistenta din emitor
uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor','white',...
'ForegroundColor','black',...
'HorizontalAlignment','center',...
'Position',[0.1 0.5 0.2 0.1],...
'String','Re [kOhm]',...
'Parent',Butoane_parametrii);
uicontrol('Style','edit',...
'Units','normalized',...
'Position',[0.5 0.5 0.3 0.1],...
'String',Re,...
'Callback','Re=str2num(get(gco,''string'')),close;interface(A,VAl,beta,Rc,Re,Rb1,Rb2,Rl,f,Ie,valoare);',...
'Parent',Butoane_parametrii);

%-----------buton pentru rezistenta 1 din baza
uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor','white',...
'ForegroundColor','black',...
'HorizontalAlignment','center',...
'Position',[0.1 0.4 0.2 0.1],...
'String','Rb1 [kOhm]',...
'Parent',Butoane_parametrii);
uicontrol('Style','edit',...
'Units','normalized',...
'Position',[0.5 0.4 0.3 0.1],...
'String',Rb1,...
'Callback','Rb1=str2num(get(gco,''string'')),close;interface(A,VAl,beta,Rc,Re,Rb1,Rb2,Rl,f,Ie,valoare);',...
'Parent',Butoane_parametrii);

%-----------buton pentru rezistenta 2 din baza
uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor','white',...
'ForegroundColor','black',...
'HorizontalAlignment','center',...
'Position',[0.1 0.3 0.2 0.1],...
'String','Rb2 [kOhm]',...
'Parent',Butoane_parametrii);
uicontrol('Style','edit',...
'Units','normalized',...
'Position',[0.5 0.3 0.3 0.1],...
'String',Rb2,...
'Callback','Rb2=str2num(get(gco,''string'')),close;interface(A,VAl,beta,Rc,Re,Rb1,Rb2,Rl,f,Ie,valoare);',...
'Parent',Butoane_parametrii);

%-----------buton pentru rezistenta load
uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor','white',...
'ForegroundColor','black',...
'HorizontalAlignment','center',...
'Position',[0.1 0.2 0.2 0.1],...
'String','Rl [kOhm]',...
'Parent',Butoane_parametrii);
uicontrol('Style','edit',...
'Units','normalized',...
'Position',[0.5 0.2 0.3 0.1],...
'String',Rl,...
'Callback','Rl=str2num(get(gco,''string'')),close;interface(A,VAl,beta,Rc,Re,Rb1,Rb2,Rl,f,Ie,valoare);',...
'Parent',Butoane_parametrii);

%-----------buton pentru frecventa
uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor','white',...
'ForegroundColor','black',...
'HorizontalAlignment','center',...
'Position',[0.1 0.1 0.2 0.1],...
'String','f [Hz]',...
'Parent',Butoane_parametrii);
uicontrol('Style','edit',...
'Units','normalized',...
'Position',[0.5 0.1 0.3 0.1],...
'String',f,...
'Callback','f=str2num(get(gco,''string'')),close;interface(A,VAl,beta,Rc,Re,Rb1,Rb2,Rl,f,Ie,valoare);',...
'Parent',Butoane_parametrii);

%-----------buton pentru curentul din emitor
uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor','white',...
'ForegroundColor','black',...
'HorizontalAlignment','center',...
'Position',[0.1 0 0.2 0.1],...
'String','Ie [mA]',...
'Parent',Butoane_parametrii);
uicontrol('Style','edit',...
'Units','normalized',...
'Position',[0.5 0 0.3 0.1],...
'String',Ie,...
'Callback','Ie=str2num(get(gco,''string'')),close;interface(A,VAl,beta,Rc,Re,Rb1,Rb2,Rl,f,Ie,valoare);',...
'Parent',Butoane_parametrii);



%-----------reprezentarea circuitului
subplot(223)
Imag= imread('imagine_proiect.jpg');
imshow(Imag);

uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor','white',...
'ForegroundColor','black',...
'HorizontalAlignment','center',...
'FontSize',18,...
'Position',[0.13, 0.08 0.338 0.05],...
'String','Schema circuit');



%-----------valorile calculate a parametriilor de semnal mic
RadioGroup=uibuttongroup('Visible','on',...
'BackgroundColor','white',...
'ForegroundColor','black',...
'Title','Parametrii de semnal mic',...
'FontSize',12,...
'TitlePosition','centertop',...
'Tag','radiobutton',...
'Position',[0.01 0.45 0.25 0.3]);


%-----------butoane pentru parametrii de semnal mic
uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor','white',...
'ForegroundColor','black',...
'HorizontalAlignment','center',...
'Position',[0.1 0.8 0.1 0.2],...
'String','gm',...
'Parent',RadioGroup);

uicontrol('Style','text',...
'Units','normalized',...
'Position',[ 0.5 0.9 0.3 0.1],...
'String',gm,...
'Callback','gm=str2num(get(gco,''string'')),close;interface(A,VAl,beta,Rc,Re,Rb1,Rb2,Rl,f,Ie,valoare);',...
'Parent',RadioGroup);

uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor','white',...
'ForegroundColor','black',...
'HorizontalAlignment','center',...
'Position',[0.1 0.6 0.2 0.2],...
'String','rbe[kOhm]',...
'Parent',RadioGroup);
uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.5 0.7 0.3 0.1],...
'String',rbe,...
'Parent',RadioGroup,...
'Callback','rbe=str2num(get(gco,''string'')),close;interface(A,VAl,beta,Rc,Re,Rb1,Rb2,Rl,f,Ie,valoare);');

%-----------buton pentru amplificarea in tensiune
uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor','white',...
'ForegroundColor','black',...
'HorizontalAlignment','center',...
'Position',[0.1 0.4 0.2 0.2],...
'String','Av',...
'Parent',RadioGroup);
uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.5 0.5 0.3 0.1],...
'String',Av,...
'Callback','Av=str2num(get(gco,''string'')),close;interface(A,VAl,beta,Rc,Re,Rb1,Rb2,Rl,f,Ie,valoare);',...
'Parent',RadioGroup);

%-----------buton pentru rezistenta de intrare
uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor','white',...
'ForegroundColor','black',...
'HorizontalAlignment','center',...
'Position',[0.1 0.2 0.2 0.2],...
'String','Ri[kOhm]',...
'Parent',RadioGroup);
uicontrol('Style','text',...
'Units','normalized',...
'String',Ri,...
'Position',[0.5 0.3 0.3 0.1],...
'Callback','Ri=str2num(get(gco,''string'')),close;interface(A,VAl,beta,Rc,Re,Rb1,Rb2,Rl,f,Ie,valoare);',...
'Parent',RadioGroup);

%-----------buton pentru rezistenta de iesire 
uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor','white',...
'ForegroundColor','black',...
'HorizontalAlignment','center',...
'Position',[0.1 0.0 0.2 0.2],...
'String','Ro[kOhm]',...
'Parent',RadioGroup);
uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.5 0.1 0.3 0.1],...
'String',Ro,...
'Callback','Ro=str2num(get(gco,''string'')),close;interface(A,VAl,beta,Rc,Re,Rb1,Rb2,Rl,f,Ie,valoare);',...
'Parent',RadioGroup);
         


%-----------reprezentarea semnalelor de intrare si de iesire---------------

switch(valoare)
    case 1                              %-----------Semnal sinusoidal------

%-----------semnalul de intrare
vi=A.*sin(2.*pi.*f.*t);
subplot(222);
plot(t,vi,'k','Linewidth', 2);
title('Vi(t) - tensiunea de intrare');
grid on;
hold on;
xlabel('Timp [s]');
ylabel('Amplitudine [V]');

%-----------semnalul de iesire
vO=Av.*A.*sin(2.*pi.*f.*t);             %-----------am scos componenta continua
for i = 1:length(vO)
    if vO(i) > VAl
        vO(i)  = VAl;
    elseif vO(i)<-VAl
        vO(i) = -VAl;
    end
end
subplot(224);
plot(t,vO,'k','Linewidth', 2);
title('Vo(t) - tensiunea de iesire');
grid on;
hold on;
xlabel('Timp [s]');
ylabel('Amplitudine [V]');

%-----------buton pentru reset la valorile prestabilite 
uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.92 0.95 0.08 .05],...
'BackgroundColor','#762659',...
'ForegroundColor','white',...
'String','Reset',...
'Callback','close;interface(0.01,20,100,4,0.4,110,10,4,100,2,1)');

    case 2                              %-----------Semnal triunghiular----

%-----------semnalul de intrare
vi=(2.*A/pi)*asin(sin(2.*pi.*f.*t));
subplot(222);
plot(t,vi,'k','Linewidth', 2);
title('Vi(t) - tensiunea de intrare');
grid on;
hold on;
xlabel('Timp [s]');
ylabel('Amplitudine [V]');

%-----------semnalul de iesire
vO=Av.*(2.*A/pi)*asin(sin(2.*pi.*f.*t));         %-----------am scos componenta continua
for i = 1:length(vO)
    if vO(i) > VAl
        vO(i)  = VAl;
    elseif vO(i)<-VAl
        vO(i) = -VAl;
    end
end
subplot(224);
plot(t,vO,'k','Linewidth', 2');
title('Vo(t) - tensiunea de iesire');
grid on;
hold on;
xlabel('Timp [s]');
ylabel('Amplitudine [V]');

%-----------buton pentru reset la valorile prestabilite 
uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.92 0.95 0.08 .05],...
'BackgroundColor','#762659',...
'ForegroundColor','white',...
'String','Reset',...
'Callback','close;interface(0.01,20,100,4,0.4,110,10,4,100,2,2)');

end



%-----------shortcut la Documentatie
doc=uimenu('Label','Documentație');
uimenu(doc,'Label','Teorie',...
           'Callback','open(''Proiect_GAC_VladCristianAdrian.docx'')');
uimenu(doc,'Label','Prezentare',...
           'Callback','open(''Proiect_GAC_VladCristianAdrian.pptx'')');



%-----------buton pentru EROARE
if (f<=0 || Rb1<=0 || Rb2<=0 || Re<=0 || Rl<=0 || Rc<=0)
    uicontrol('Style','text',...
        'Units','normalized',...
         'Position',[0 0 0.1 0.05],...
         'FontSize',14,...
         'Foregroundcolor','black',...
         'String','EROARE');
end

end